### ISSUE TITLE
bib not working on my macine

### ISSUE THREAD

**Issue by irisyupingren** [VictorCMiraldo/hs-fragem#19]
On the paper branch, I'm having trouble getting the reference right. I copied and pasted what I had before and it was working on a vanilla latex file. 

There were a series of error messages like this:
"Package natbib Warning: Citation `forte1959schenker' on page 1 undefined on inp
ut line 378."

Just wondering if this is a setting problem on my machine?

**Comment by VictorCMiraldo** [comment]
@irisyupingren , you have to update the auxiliary files. The makefile is prepared to handle this.
Try running `make bib && make`

**Comment by irisyupingren** [comment]
Thanks! It works now. I knew it was something silly :P
