### ISSUE TITLE
Locate and deal with unclosed notes [Feature request] [Data]

### ISSUE THREAD

**Issue by irisyupingren** [VictorCMiraldo/hs-fragem#5]
From Error message:
In running AOF, one note is missing per piece, I wonder if it's the last note of each piece? Can we locate the note and assign it a whole bar duration value? 

can1.mid
fragem: getNoteEvents: unclosed notes
CallStack (from HasCallStack):
  error, called at src/Fragem/Syntax/FromMidi.hs:113:21 in hs-fragem-0.0.0-EHfk9bWrGfR9LEuRk7FbaB:Fragem.Syntax.FromMidi
can2.mid
fragem: getNoteEvents: unclosed notes
CallStack (from HasCallStack):
  error, called at src/Fragem/Syntax/FromMidi.hs:113:21 in hs-fragem-0.0.0-EHfk9bWrGfR9LEuRk7FbaB:Fragem.Syntax.FromMidi
can3.mid
fragem: getNoteEvents: unclosed notes
CallStack (from HasCallStack):
  error, called at src/Fragem/Syntax/FromMidi.hs:113:21 in hs-fragem-0.0.0-EHfk9bWrGfR9LEuRk7FbaB:Fragem.Syntax.FromMidi
can4.mid
fragem: getNoteEvents: unclosed notes
CallStack (from HasCallStack):
  error, called at src/Fragem/Syntax/FromMidi.hs:113:21 in hs-fragem-0.0.0-EHfk9bWrGfR9LEuRk7FbaB:Fragem.Syntax.FromMidi
cnt1.mid
fragem: getNoteEvents: unclosed notes
CallStack (from HasCallStack):
  error, called at src/Fragem/Syntax/FromMidi.hs:113:21 in hs-fragem-0.0.0-EHfk9bWrGfR9LEuRk7FbaB:Fragem.Syntax.FromMidi
cnt2.mid
fragem: getNoteEvents: unclosed notes
CallStack (from HasCallStack):
  error, called at src/Fragem/Syntax/FromMidi.hs:113:21 in hs-fragem-0.0.0-EHfk9bWrGfR9LEuRk7FbaB:Fragem.Syntax.FromMidi
cnt3.mid
fragem: getNoteEvents: unclosed notes
CallStack (from HasCallStack):
  error, called at src/Fragem/Syntax/FromMidi.hs:113:21 in hs-fragem-0.0.0-EHfk9bWrGfR9LEuRk7FbaB:Fragem.Syntax.FromMidi
dou1.mid
fragem: getNoteEvents: unclosed notes
CallStack (from HasCallStack):
  error, called at src/Fragem/Syntax/FromMidi.hs:113:21 in hs-fragem-0.0.0-EHfk9bWrGfR9LEuRk7FbaB:Fragem.Syntax.FromMidi
dou2.mid
fragem: getNoteEvents: unclosed notes
CallStack (from HasCallStack):
  error, called at src/Fragem/Syntax/FromMidi.hs:113:21 in hs-fragem-0.0.0-EHfk9bWrGfR9LEuRk7FbaB:Fragem.Syntax.FromMidi
inver1.mid
fragem: getNoteEvents: unclosed notes
CallStack (from HasCallStack):
  error, called at src/Fragem/Syntax/FromMidi.hs:113:21 in hs-fragem-0.0.0-EHfk9bWrGfR9LEuRk7FbaB:Fragem.Syntax.FromMidi
inver2.mid
fragem: getNoteEvents: unclosed notes
CallStack (from HasCallStack):
  error, called at src/Fragem/Syntax/FromMidi.hs:113:21 in hs-fragem-0.0.0-EHfk9bWrGfR9LEuRk7FbaB:Fragem.Syntax.FromMidi
mir1.mid
fragem: getNoteEvents: unclosed notes
CallStack (from HasCallStack):
  error, called at src/Fragem/Syntax/FromMidi.hs:113:21 in hs-fragem-0.0.0-EHfk9bWrGfR9LEuRk7FbaB:Fragem.Syntax.FromMidi
mir2.mid
fragem: getNoteEvents: unclosed notes
CallStack (from HasCallStack):
  error, called at src/Fragem/Syntax/FromMidi.hs:113:21 in hs-fragem-0.0.0-EHfk9bWrGfR9LEuRk7FbaB:Fragem.Syntax.FromMidi
reg1.mid
fragem: getNoteEvents: unclosed notes
CallStack (from HasCallStack):
  error, called at src/Fragem/Syntax/FromMidi.hs:113:21 in hs-fragem-0.0.0-EHfk9bWrGfR9LEuRk7FbaB:Fragem.Syntax.FromMidi
reg2.mid
fragem: getNoteEvents: unclosed notes
CallStack (from HasCallStack):
  error, called at src/Fragem/Syntax/FromMidi.hs:113:21 in hs-fragem-0.0.0-EHfk9bWrGfR9LEuRk7FbaB:Fragem.Syntax.FromMidi
tri1.mid
fragem: getNoteEvents: unclosed notes
CallStack (from HasCallStack):
  error, called at src/Fragem/Syntax/FromMidi.hs:113:21 in hs-fragem-0.0.0-EHfk9bWrGfR9LEuRk7FbaB:Fragem.Syntax.FromMidi
tri2.mid
fragem: getNoteEvents: unclosed notes
CallStack (from HasCallStack):
  error, called at src/Fragem/Syntax/FromMidi.hs:113:21 in hs-fragem-0.0.0-EHfk9bWrGfR9LEuRk7FbaB:Fragem.Syntax.FromMidi
unfin.mid
fragem: getNoteEvents: unclosed notes
CallStack (from HasCallStack):
  error, called at src/Fragem/Syntax/FromMidi.hs:113:21 in hs-fragem-0.0.0-EHfk9bWrGfR9LEuRk7FbaB:Fragem.Syntax.FromMidi

**Comment by VictorCMiraldo** [comment]
https://music.stackexchange.com/questions/49635/ill-formed-midi-files-note-ons-and-note-offs-dont-correspond

**Comment by VictorCMiraldo** [comment]
Seems like the velocity 0 trick worked; and as it turns out, missing time signatures are indeed supposed to be a 4/4.

e18d831469d924b6aafbdac1a05785486981c9bf

18bb534484d466cb8fd3ea6d87e4bd899667cc81

**Comment by VictorCMiraldo** [comment]
@irisyupingren

**Comment by irisyjohnson** [comment]
Thank you! It's working on the art of fugues now!
But on Czerny, it's giving all zeros. Issues for another time...
